VERSION 0.7

deps:
    FROM node:16-alpine

    WORKDIR /app
    ENV NODE_ENV production

    # Install dependencies
    RUN apk update && \
        apk add \
        build-base \
        gcc \
        autoconf \
        automake \
        zlib-dev \
        libpng-dev \
        nasm \
        bash \
        vips-dev

    COPY ./package*.json ./
    RUN npm install

    SAVE IMAGE --cache-hint

build:
    FROM +deps

    ARG env=dev
    ARG REACT_APP_FRONTEND_URL="https://app.${env}.projectcatalyst.io"
    ARG REACT_APP_BASE_URL="https://backend.${env}.projectcatalyst.io"
    ARG REACT_APP_CATALYST_CORE_API_URL="https://core.${env}.projectcatalyst.io"
    ARG REACT_APP_CARDANOSCAN_BASE_URL="https://preprod.cardanoscan.io/"

    COPY . .
    RUN npm run build

    SAVE ARTIFACT /app /app

docker:
    FROM node:16-alpine

    EXPOSE 1337

    WORKDIR /app
    ENV NODE_ENV production
    ARG env=dev

    # Install runtime deps
    RUN apk update && \
        apk add \
        vips-dev

    COPY (+build/app --env=${env}) /app

    CMD ["npm", "run", "develop"]

    ARG registry
    ARG tag=latest
    SAVE IMAGE --push ${registry}voting-center-backend:${tag}
