version: "3"

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gvcDBtest
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 2s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432

  backend:
    image: voting-center-backend:latest
    environment:
      - NODE_ENV=development
      - ENV=dev
      - HOST=0.0.0.0
      - PORT=1337
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=gvcDBtest
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - APP_KEYS=oHALYxehalk5k02qBZcTbg==,iGa6t2cysUfm+X3F+fdgNQ==,DBF+oC+F3NzIOWEYNG81iA==,NzoFHf+LKaodqYjEpUs0Fw==
      - API_TOKEN_SALT=Mda37Yk/R5CqywOygvaZ4Q==
      - ADMIN_JWT_SECRET=kEdxKbjGcR0fqzRKQop0gA==
      - JWT_SECRET=zniSMBNuX91kZznZZm9s4g==
      - PUBLIC_URL=http://localhost:1337
      - SENTRY_DSN=https://75fd743253ed433090fb7e34d7f653ba@o1231424.ingest.sentry.io/4503890553602048
      - BLOCKFROST_KEY=preprodLwAS09DX7BdekzbGoYMMsyLv4vPTYCUX
      - BLOCKFROST_URL=https://cardano-preprod.blockfrost.io/api/
    depends_on:
      postgres:
        condition: service_healthy
