VERSION 0.7

deps:
    FROM node:16-alpine

    WORKDIR /app
    ENV NODE_ENV production

    COPY package.json .
    RUN npm install --production
    SAVE IMAGE --cache-hint

build:
    FROM +deps

    ARG env=dev
    ARG REACT_APP_BASE_URL="https://backend.${env}.projectcatalyst.io"
    ARG REACT_APP_CATALYST_CORE_API_URL="https://api.${env}.projectcatalyst.io"
    ARG REACT_APP_FRONTEND_URL="https://app.${env}.projectcatalyst.io"
    ARG REACT_APP_SHARETHIS_PROPERTY_ID="64b6b417d695f60013b423bf" 
    ARG STRAPI_LOG_LEVEL=trace

    COPY . .

    RUN npm run react-inject-env && npm run build

    SAVE ARTIFACT /app/build /app/build

docker:
    FROM nginx:stable-alpine-slim

    EXPOSE 80

    WORKDIR /app
    ENV NODE_ENV production
    ARG env=dev

    COPY (+build/app/build --env=${env}) /usr/share/nginx/html
    COPY nginx.conf /etc/nginx/conf.d/default.conf

    CMD ["nginx", "-g", "daemon off;"]

    ARG registry
    ARG tag=latest
    SAVE IMAGE --push ${registry}voting-center-frontend:${tag}